# -*- coding: utf-8 -*-
"""salesdataanalysisdavidmariaolandese.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Olandesedavidmaria/b37f492098acf9de686c67cc07ca6962/salesdataanalysisdavidmariaolandese.ipynb

#1. Prepare Data for Analysis

share link: https://colab.research.google.com/drive/1wNZspRT9fw2bLwr_HWBL9o6cq63uARSE?usp=sharing
"""

#importing all required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

#read the csv file as DataFrame

df=pd.read_csv('Sales.csv')
print("The file loaded successfully")

#Print the dataframe
df.head()

#Print the dataframe shape
(row, col)=df.shape
print (f"the dataframe has{row} rows and {col} columns." )

#Check for the missing values
total_missing_values=df.isnull().sum()
print("total missing vakues are:", total_missing_values)

"""we found there are no missing values in the Dataframe

---


"""

#Check for no_non_missing values
no_non_missing_values=df.notnull().sum().sum()
print("total no non missing vakues are:", no_non_missing_values)
#there are 45360 non-null missing values

"""#2.Normalize Data for Analysis"""

df.head()

df.info()

#we create a dataframe containing just the quantitatives variables from the existing dataframe
df_data_only=df[['Unit','Sales']].copy()
df_data_only.head()

#we need to Normalize our data
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

normalize_data=scaler.fit_transform(df_data_only)
normalize_data[:5]
normalize_data_df=pd.DataFrame(normalize_data, columns=["Unit","Sales"])
normalize_data_df.head()
#now datas are in the same range (0 to 1)

#Check the min and maz values of each column. We normalized so the would be (almnost) 0 and almost 1)
normalize_data_df["Unit"].min(), normalize_data_df["Unit"].max()

normalize_data_df["Sales"].min(), normalize_data_df["Sales"].max()

print("Before Normalization")
print(df_data_only["Unit"].min(), df_data_only["Unit"].max())
print("After Nomalization")
print(normalize_data_df["Unit"].min(), normalize_data_df["Unit"].max())

print("Before Normalization")
print(df_data_only["Sales"].min(), df_data_only["Sales"].max())
print("After Nomalization")
print(normalize_data_df["Sales"].min(), normalize_data_df["Sales"].max())

"""#3. Visualize the overall trend"""

#first we need to convert Date column to datatime datatype
df["Date"] = pd.to_datetime(df['Date'], format="%d-%b-%y")
df.info()

#Groupby the date and sum Unit and Sales
daily_data=df.groupby('Date')[["Unit","Sales"]].sum().reset_index()
daily_data

#Plot the graph between Date and Unit
plt.plot(daily_data['Date'], daily_data['Unit'],linewidth = 1, marker= "o")
plt.title("Date vs Unit Line Plot")
plt.xlabel("Date")
plt.ylabel("Unit")
plt.tick_params(axis= 'x', rotation= 45)
plt.show()

#Plot the graph between Date and Sales
plt.plot(daily_data['Date'], daily_data['Sales'],color='r', linewidth = 1, marker= "*")
plt.title("Date vs Sales Line Plot")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.tick_params(axis= 'x', rotation= 45)
plt.show()

"""It is the very clear from te line plot that the overal sales goes down in the month of November

#4. Analyze Monthly Data
"""

# Chunk the quartely data into monthly data
#october
df_oct = df.loc[(df['Date'] >= '2020-10-1') & (df['Date'] < '2020-11-1')].copy()
df_oct.head()

#november
df_nov = df.loc[(df['Date'] >= '2020-11-1') & (df['Date'] < '2020-12-1')].copy()
df_nov.head()

#december
df_dec = df.loc[(df['Date'] >= '2020-12-1') & (df['Date'] < '2021-1-1')].copy()
df_dec.head()

print("Summary of Monthly Data:")
print("===============================================")
print(f"Number of records in October : {len(df_oct)}")
print(f"Number of records in November : {len(df_nov)}")
print(f"Number of records in December : {len(df_dec)}")

"""#5. Describe Data"""

#Describe entire dataset
df.describe(include='all')

#Description for October
df_oct[["Unit", "Sales"]].describe()

# Description for November
df_nov[["Unit", "Sales"]].describe()

# Description for December
df_dec[["Unit", "Sales"]].describe()

"""all the distribution will be right skewed, because the mean is greater than the median.

#6. Analyze Unit Data
"""

plt.boxplot(df_oct["Unit"])
plt.title("Unit distribution across October month")

plt.hist(df_oct["Unit"], bins =50)
plt.title("Histogram distribution across October Month for Unit")
plt.show()

plt.boxplot(df_nov["Unit"])
plt.title("Unit distribution across November month")

plt.hist(df_nov["Unit"], bins =50)
plt.title("Histogram distribution across November Month for Unit")
plt.show()

plt.boxplot(df_dec["Unit"])
plt.title("Unit distribution across Dicember month")

"""We can see there are 3 outliers in Dec ( > of the value of 60)"""

plt.hist(df_dec["Unit"], bins =50)
plt.title("Histogram distribution across December Month for Unit")
plt.show()

df.head(10)

def extract_month_from_date(date):
  return date.strftime("%b")

date = df.loc[2750, "Date"]
df["Month"] = df['Date'].apply(extract_month_from_date)
df.head(10)

sns.boxplot(x="Month", y="Unit", data = df)
plt.show()

sns.boxplot(x="Month", y="Sales", data = df)
plt.title("Sales distribution across each month")
plt.show()

"""#7. Explore Monthly Plots and Analysis"""

print("=============Overall Unit/Sales Figure====================")
print(f"Total units sold : {df["Unit"].sum()}")
print(f"Total sales  : {df["Sales"].sum()}")

# Units Sold in each month
print("=============Unit Figure====================")
print(f"Total units in October : {df_oct["Unit"].sum()}")
print(f"Total units in Novemebr : {df_nov["Unit"].sum()}")
print(f"Total units in December : {df_dec["Unit"].sum()}")

print("=============Sales Figure====================")
print(f"Total sales in October : {df_oct["Sales"].sum()}")
print(f"Total sales in Novemebr : {df_nov["Sales"].sum()}")
print(f"Total sales in December : {df_dec["Sales"].sum()}")

df_oct_sales = df_oct.groupby("Date")["Sales"].sum().reset_index()
# Consolidated 3-months sales plot
plt.figure(figsize= (15, 10))
plt.plot(df_oct_sales["Date"], df_oct_sales["Sales"], color = "g", marker= "o")
plt.title("Sales record in October")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

df_nov_sales = df_nov.groupby("Date")["Sales"].sum().reset_index()
# Consolidated 3-months sales plot
plt.figure(figsize= (15, 10))
plt.plot(df_nov_sales["Date"], df_nov_sales["Sales"], color = "r", marker= "o")
plt.title("Sales record in November")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

df_dec_sales = df_dec.groupby("Date")["Sales"].sum().reset_index()
# Consolidated 3-months sales plot
plt.figure(figsize= (15, 10))
plt.plot(df_dec_sales["Date"], df_dec_sales["Sales"], color = "b", marker= "o")
plt.title("Sales record in December")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

# Extract the day number in month
def extract_date_from_datetime(date):
  return date.strftime("%d")


df_oct["Day"] = df_oct["Date"].apply(extract_date_from_datetime)
df_oct_sale_daywise = df_oct.groupby("Day")["Sales"].sum().reset_index()

df_oct_sale_daywise.rename(columns = {"Sales": "Oct_Sales"}, inplace =True)

df_nov["Day"] = df_nov["Date"].apply(extract_date_from_datetime)
df_nov_sale_daywise = df_nov.groupby("Day")["Sales"].sum().reset_index()
df_nov_sale_daywise.rename(columns = {"Sales": "Nov_Sales"}, inplace =True)

df_dec["Day"] = df_dec["Date"].apply(extract_date_from_datetime)
df_dec_sale_daywise = df_dec.groupby("Day")["Sales"].sum().reset_index()
df_dec_sale_daywise.rename(columns = {"Sales": "Dec_Sales"}, inplace =True)

df_oct_sale_daywise.head()

df_nov_sale_daywise.head()

df_dec_sale_daywise.head()

plt.figure(figsize= (15, 10))
plt.plot(df_oct_sale_daywise["Day"], df_oct_sale_daywise["Oct_Sales"], color = "r", marker= "o")
plt.plot(df_nov_sale_daywise["Day"], df_nov_sale_daywise["Nov_Sales"], color = "b", marker= "*")
plt.plot(df_dec_sale_daywise["Day"], df_dec_sale_daywise["Dec_Sales"], color = "g", marker= "+")
plt.title("Day wise Sales")
plt.xlabel("Day")
plt.ylabel("Sales")
plt.show()

# Extract the day of week
def extract_weekday_from_datetime(date):
  return date.strftime("%a")


df_oct["WeekDay"] = df_oct["Date"].apply(extract_weekday_from_datetime)
df_oct_sale_daywise = df_oct.groupby("WeekDay")["Sales"].sum().reset_index()

df_oct_sale_daywise.rename(columns = {"Sales": "Oct_Sales"}, inplace =True)

df_nov["WeekDay"] = df_nov["Date"].apply(extract_weekday_from_datetime)
df_nov_sale_daywise = df_nov.groupby("WeekDay")["Sales"].sum().reset_index()
df_nov_sale_daywise.rename(columns = {"Sales": "Nov_Sales"}, inplace =True)

df_dec["WeekDay"] = df_dec["Date"].apply(extract_weekday_from_datetime)
df_dec_sale_daywise = df_dec.groupby("WeekDay")["Sales"].sum().reset_index()
df_dec_sale_daywise.rename(columns = {"Sales": "Dec_Sales"}, inplace =True)

df_oct_sale_daywise

plt.figure(figsize= (15, 10))
plt.plot(df_oct_sale_daywise["WeekDay"], df_oct_sale_daywise["Oct_Sales"], color = "r", marker= "o")
plt.plot(df_nov_sale_daywise["WeekDay"], df_nov_sale_daywise["Nov_Sales"], color = "b", marker= "*")
plt.plot(df_dec_sale_daywise["WeekDay"], df_dec_sale_daywise["Dec_Sales"], color = "g", marker= "+")
plt.title("Day wise Sales")
plt.xlabel("Day")
plt.ylabel("Sales")
plt.show()

"""# 8. Obtain a Comprehensive Snapshot"""

# Overall Metric of data
total_record = len(df)
total_units = df["Unit"].sum()
total_sales = df["Sales"].sum()
average_units = df["Unit"].mean()
average_sales = df["Sales"].mean()

print("=========Overll Data Metrics ========")
print(f"Total number of records : {total_record}")
print(f"Total units : {total_units}")
print(f"Total Sales : {total_sales}")
print(f"Average number of units : {average_units}")
print(f"Average Sales : {average_sales}")
print()
print("=========Overll Data Metrics for October ========")
print(f"Total number of records : {len(df_oct)}")
print(f"Total units : {df_oct["Unit"].sum()}")
print(f"Total Sales : {df_oct["Sales"].sum()}")
print(f"Average number of units : {df_oct["Unit"].mean()}")
print(f"Average Sales : {df_oct["Sales"].mean()}")
print()
print("=========Overll Data Metrics for November ========")
print(f"Total number of records : {len(df_nov)}")
print(f"Total units : {df_nov["Unit"].sum()}")
print(f"Total Sales : {df_nov["Sales"].sum()}")
print(f"Average number of units : {df_nov["Unit"].mean()}")
print(f"Average Sales : {df_nov["Sales"].mean()}")
print()
print("=========Overll Data Metrics for December ========")
print(f"Total number of records : {len(df_dec)}")
print(f"Total units : {df_dec["Unit"].sum()}")
print(f"Total Sales : {df_dec["Sales"].sum()}")
print(f"Average number of units : {df_dec["Unit"].mean()}")
print(f"Average Sales : {df_dec["Sales"].mean()}")

"""# 9. Analyze statewise Sales in United States"""

df.head()

df["State"].unique()

state_wise_data = df.groupby("State")[["Unit", "Sales"]].sum().reset_index()
state_wise_data

plt.bar(state_wise_data["State"], state_wise_data["Unit"])
plt.title("Statewise Units")
plt.xlabel("State")
plt.ylabel("Units")
plt.show()

plt.bar(state_wise_data["State"], state_wise_data["Sales"])
plt.title("Statewise Sales")
plt.xlabel("State")
plt.ylabel("Sales")
plt.show()

df["Unit"].mean()